input {
  kafka {
    bootstrap_servers => "kafka:29092"
    topics => ["topic-listas-compras"]
    codec => json
    group_id => "logstash_consumer_group"
    auto_offset_reset => "earliest"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "listas-compras-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
