<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>app_backend_produto.domain</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Handlers\Produto\AdicionarProdutoCommandHandler.cs" />
    <Compile Remove="Handlers\Produto\AtualizarProdutoCommandHandler.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Handlers\Produto\AdicionarProdutoCommandHandler.cs" />
    <None Include="Handlers\Produto\AtualizarProdutoCommandHandler.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="7.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Library\Core_Logs\Core_Logs.csproj" />
  </ItemGroup>

</Project>

